### ISSUE TITLE
Sparse connectivity matrices on Loihi 2

### ISSUE THREAD

**Issue by ashishrao7** [lava-nc/lava#436]
### User story

As a user, I want to express sparse connectivity matrices on Loihi 2 more resource-efficiently to enable building larger architectures.

### Conditions of satisfaction
- Users can specify the connectivity matrix via a sparse matrix.
- Resources on Loihi 2 are lower than using the current implementation of the `Dense` Process for sparsely populated connectivity matrices.
- The implementation uses Loihi 2 features to compress the connectivity matrix.
- The expected behavior is the same of the `Dense` Process.
- Unit testing of this new feature does not create code duplication with the `Dense` Process.

### Acceptance tests
- Consistent results between Dense and Sparse
- Include corner cases and different sizes

### Tasks

- [x] Get familiar and try out current implementation (1h)
- [x] Write unit tests for `Sparse` demonstrating the usage (2h)
- [x] Implement NcVar for `scipy.csr_matrix` (1d)
- [x] Implement/adapt NcProcModel including delays and learning (2h)
- [x] Implement tests for corner cases (0.5d)
- [x] Benchmark the speed (power consumption) and compare to `Dense` (0.5d)
- [x] Code review (0.5d)
- [x] Merge (1h)
