### ISSUE TITLE
Explore designs for composing Process features

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#558]
### User story

As an NCL developer, I want to understand the different designs for composing Lava Process features to facilitate a decision on how to implement the feature.

### Conditions of satisfaction
- Design choices have been explored
- All viable design choices are documented in a slide deck, as code snippets
- Designs have been presented to a wider forum
- A decision has been made for a design

### Tasks
- [x] Open discussion and brainstorming session with the team
- [x] Sync with Garrick to discuss the overall topic of micro-coded vs hard-coded neurons (STDP, etc.)

(Optional - depending on sync):
- [x] Create a slide deck with:
    - [x] the current problems/possible solutions of composing process features for CPU compute resource
    - [x] the foreseeable problems with composing features of micro-coded processes (STDP, etc.)
    - [x] List what the differences/missing features will be for hard-coded and micro-coded neurons
 - [ ] ~~Discuss the above issues in a meeting with Garrick/Andreas to find a path using micro-coded neurons with processes~~

### Stories
Implement design: https://github.com/lava-nc/lava/issues/550
Implement composable ucoded neurons: https://github.com/intel-collab/frameworks.ai.lava.lava-loihi/issues/138
