### ISSUE TITLE
Explore designs for IO to/from Lava

### ISSUE THREAD

**Issue by gkarray** [lava-nc/lava#577]
### User story
As an NCL developer, I want to explore the different designs for inputting data to Lava Processes and getting data out of Lava Processes to facilitate a decision on how to implement the feature.

### Conditions of satisfaction
- Design choices have been explored
- All viable design choices are documented in a slide deck
- Designs have been presented to a wider forum
- A decision has been made for a design

### Tasks
- [x] Create a slide deck, describing the 2 different design choices [1 day]
- [x] Prototype the 2 design choices with code snippets [1 day]
- [x] Meeting with x to discuss the documented design choices [1h x 4]
- [x] Integrate the feedback of the meeting, make a decision and communicate the decision -> create an user story [1 day]

**Comment by mathisrichter** [comment]
This could be more explicit in stating that it is about getting data into/out of Lava in general, not just into/out of a Process. Otherwise it could sound like this is already done by Ports.
