### ISSUE TITLE
Change Loihi Learning Rule during runtime in simulation

### ISSUE THREAD

**Issue by weidel-p** [lava-nc/lava#582]
### User story
As a user being interested in plasticity, I want to be able to exchange parameters of the learning rule during runtime to avoid the necessity to re-create the complete network.

### Conditions of satisfaction
- Parameters of the learning rule can be changed during runtime for the CPU backend
- Parameters of the learning rule create Vars on the Connection and Neuron Process(Models)
- The Vars of the Dense/Neuron Process(Models) have get/set functions
- Tests have been written to demonstrate the expected behavior for each parameter of the learning rules
- Tests have been written for parameters inflicting the post-synaptic neuron
- Code has been reviewed and merged

### Acceptance tests
- The get/set functions of all parameters are tested at the Dense Process
- The get/set functions of all parameters are tested at the Neuron Process
- Test for invalid values

### Tasks
- [ ] Implementation of tests (PW, 1/2 day)
- [x] Implementation of String LavaType (PW)
- [ ] Unit tests for String LavaType (PW, 1 hour)
- [x] Implementation of Connection Vars (PW)
- [ ] Implementation of Neuron Vars (PW, 1/2 day)
- [ ] Documentation (PW, 1/2 day)
- [ ] PR and review (PW, GK, 1/2 day)
- [ ] Merge to main (PW, 1 hour)
