### ISSUE TITLE
Automated response time statistics

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#588]
### User story
As a Lava maintainer, I want to know how quickly we respond to support requests on Github to move toward shorter response times in a data-driven way.

Note: Response time is measured by the time elapsed between opening an issue and the first written response by someone other than the original author. For Github issues, it should also require that a Lava maintainer has been assigned to the issue.

### Conditions of satisfaction
- Response time on bug reports are captured (all repositories)
- Response time on feature requests are captured (all repositories)
- Response time in discussion forum are captured (all repositories)
- Response times are visualized in a graph
- A summary report can be generated for a given time frame.
- Monthly summary against OKR targets
- Possibility to filter for support requests originating from the wider community vs. from within NCL.

### Acceptance tests
- Script which allows to specify a time frame to gather information and outputs a table with bug, feature and discussion response times as well as a graph.
- Script allows to specify response time targets (OKR) and creates a summary against this targets.

### Tasks
- [ ] Create script skeleton for the desired features with dummy results (PP, 4 hours)
- [ ] Write unit tests against dummy results (PP, 2 hours)
- [ ] Review output and visualization with team (1 hour)
- [ ] Exchange dummy results with GitHub API calls to get real results (PP, 1 day)
- [ ] Review and merge (4 hours)

**Comment by PhilippPlank** [comment]
![response time](https://user-images.githubusercontent.com/32519998/215480422-300382d7-dd5c-4b55-923c-ae35f5010408.png)

I would suggest something like that for the visualization. Written report would be a table.

@mathisrichter If this is what you had in mind, then this should be not problem to implement.

**Comment by mathisrichter** [comment]
Yes looks good

**Comment by PhilippPlank** [comment]
Done, the script can be found here:
https://github.com/lava-nc/lava-github-stats/blob/main/response_time/response_time.py

The automatic script will run once a month (on day 7) for the time span of the month before and add a line in this table: https://github.com/lava-nc/lava-github-stats/blob/main/response_time/response_time.csv
