### ISSUE TITLE
Event-based `.aedat` input source (vision) in Lava

### ISSUE THREAD

**Issue by gkarray** [lava-nc/lava#603]
### User story
As a user, I want to be able to feed event-based vision data coming from .aedat files to Lava Processes in order to build SNN algorithms harnessing event-based vision data.

Note: Will add new software dependencies (e.g., `aestream`, `dv`)

### Conditions of satisfaction
- Design for batching of data (fixing number of events; duration)
- Users can feed (vision, 2D) data coming from a .aedat file to a Lava Process.

### Acceptance tests
- Lava interface to reading from an event-based video with the INIvation file format, .aedat, is available.

### Stories
- [x] #577

### Tasks
- [ ] Decide which library to use (`aestream`, `dv-python`, `dv-processing`, `aedat`, `tonic`)
- [ ] Decide on how to handle batch loading (from disk vs from memory).
- [ ] Decide on how to handle slicing (fixing number of events vs fixed time window length).
- [ ] Decide on how to handle data output (discuss with SM).
- [ ] Meet with interested parties to confirm soundness/coherence of decisions.
- [ ] Update PR#514
- [ ] Get 2 reviews, merge into main

**Comment by gkarray** [comment]
@tim-shea Yes, this issue is still relevant, although not high priority.

I am closing as it is outdated and this repository is not the right place for it.
