### ISSUE TITLE
Lava release plan

### ISSUE THREAD

**Issue by mathisrichter** [lava-nc/lava#604]
### User story

As a user, I would like to know which features the next Lava release will contain and when the release will happen, roughly.

Note: Feature-based (not time-based) releases for all repositories.

### Conditions of satisfaction

- Milestones set up in Github for all upcoming releases
- All milestones contain the features we would like to include in the release
- Estimated release date entered in milestones with a note that the date is subject to change.

### Tasks

- [x] Set up a meeting on story priorities (MR)
- [x] Meeting on story priorities (2x 1h)
- [x] Set up a meeting on release plan (MR)
- [x] Meeting on release plan (2x 1h)
- [x] Set up milestones for all upcoming releases in all repositories (MR)
- [x] Converge on a set of features for every milestone
- [x] Set tentative release time frame (MR)
