### ISSUE TITLE
Graded spike payload in pre-synaptic trace updates - `floating-pt` and `bit-approximate-loihi`

### ISSUE THREAD

**Issue by gkarray** [lava-nc/lava#606]
### User story
As a user of the learning API, I would like to use graded spike payloads to update pre-synaptic traces in order to implement more complex learning algorithms.  Especially, this is critical for prototype-based learning approaches.

Note: This story is for `floating-pt` and `bit-approximate-loihi` LearningDense PyProcessModels only.

### Conditions of satisfaction
- Works in simulation (`floating-pt` and `bit-approximate-loihi`)
- When there is a graded pre-synaptic spike on a learning-enabled synapse, this graded value could overwrite or be added to the pre-synaptic trace.
- The test coverage of the newly added module is >90%.
- The code has been reviewed and is merged into `main`.

### Acceptance tests
- Test that the pre-trace value is updated to or by the graded spike value after the pre-synaptic graded spike
- Test that pre-synaptic trace still decays exponentially with the given time constant
- Test that this pre-synaptic trace can be used in the learning engine as usual

### Tasks
- [x] Implement the feature on CPU backend (floating-point, bit-approximate)
- [x] Write unit tests
- [x] Update documentation (GK, 2h)
- [ ] Get 2 reviews (PW, EH, PP/MR?), merge into main (4h)
