### ISSUE TITLE
CPU support for Sparse Connectivity 

### ISSUE THREAD

**Issue by SveaMeyer13** [lava-nc/lava#656]
### User story
As a user, I want to express sparse connectivity matrices on CPU more resource-efficiently to enable building larger architectures.

### Conditions of satisfaction
- Users can specify the connectivity matrix via a sparse matrix.
- Bit-accurate and floating point PyProc Models are implemented.
- The expected behavior is the same of the Dense Process.
- Unit testing of this new feature does not create code duplication with the Dense Process.

### Tasks

- [x] Get familiar and try out current implementation (1h)
- [x] Write unit tests for `Sparse` CPU demonstrating the usage (2h)
- [x] Implement PyVar for `scipy.csr_matrix` (1d)
- [x] Implement bit-acc PyProcModel including delays and learning (0.5d)
- [x] Implement floating point PyProcModel including delays and learning (0.5d)
- [x] Implement tests for corner cases (0.5d)
- [ ] Code review (0.5d)
- [ ] Merge (1h)
