### ISSUE TITLE
LearningDense with non-decaying traces

### ISSUE THREAD

**Issue by gkarray** [lava-nc/lava#658]
### User story
As a user, I want to be able to run a connection Process with learning enabled (i.e LearningDense) with non-decaying traces.

### Conditions of satisfaction
- Works in simulation (`floating-pt` and `bit-approximate-loihi`) and hardware (`hard_coded`).
- Lava interface should accept a 0 decay value and treat it as non-decaying on CPU and Loihi.

### Acceptance tests
- Test that we can run a LearningDense Process with non-decaying traces `x1`, `x2`, `y1`, `y2` and `y3`.

### Tasks
- [ ] Implement the feature on all backends (4h)
- [ ] Write unit tests (4h)
- [ ] Update documentation (2h)
- [ ] Get 2 reviews (PW, EH), merge into lava-nc/main (4h)
- [ ] Get 2 reviews (PW, EH), merge into frameworks.ai.lava.lava-loihi/main (4h)

**Comment by EternalGoldenBraid** [comment]
Hey is this implemented? I cannot find examples or tests on this.
